baseurl = "https://ene.github.io/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "pt-BR"
layoutdir = "layouts"
publishdir = "public"
author = "Alexandre Magno"
title = "ENE não é ELA"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
weekform = "Monday, 2"
description = "Example blog"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
lang = "pt"
github = "ENE"
email = ""
linkedin = ""
twitter = ""
